/* eslint-disable prefer-destructuring */
/* eslint-disable prettier/prettier */
/* eslint-disable import/no-extraneous-dependencies */
const mongoose = require('mongoose');
const slugify = require('slugify');

const tractorSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  name: {
    type: String,
    required: [true, 'Un tractor trebuie să aibă un nume'],
    trim: true,
    maxlength: [
      50,
      'Numele unui tractor nu poate fi mai lung de 50 de caratere',
    ],
    minlength: [
      5,
      'Numele unui tractor nu poate fi mai scurt de 5 de caratere',
    ],
  },
  slug: String,
  power: {
    type: Number,
    required: true,

    min: [10, 'Minimum 10 cai putere'],
    max: [1200, 'Maximum 1200 de cai putere'],
  },
  maxSpeed: Number,
  category: {
    type: String,
    enum: {
      values: ['Mic', 'Mediu', 'Mare'],
      message: `Această categorie nu există`,
    },
  },
  brand: String,
  model: String,
  functioningHours: {
    type: Number,
    required: true,
  },
  maxRPM: Number,
  timeSpentInTheFarm: Number,
  usedAt: {
    type: [String],
    required: [true, 'Trebuie să se știe pentru ce este utilizat'],
    enum: {
      values: [
        'arat',
        'fertilizat',
        'semanat',
        'cultivat',
        'plantat',
        'arat feritilizat',
        'arat semanat',
        'arat cultivat',
        'arat plantat',
        'fertilizat arat',
        'fertilizat semanat',
        'fertilizat cultivat',
        'fertilizat plantat',
        'semanat arat',
        'semanat fertilizat',
        'semanat cultivat',
        'semanat plantat',
        'cultivat arat',
        'cultivat fertilizat',
        'cultivat semanat',
        'cultivat plantat',
        'plantat arat',
        'plantat fetilizat',
        'plantat semanat',
        'plantat semanat',
        'arat fertilizat semanat',
        'arat fertilizat cultivat',
        'arat fertilizat plantat',
        'arat semanat fertilziat',
        'arat semanat cultivat',
        'arat semanat plantat',
        'arat cultivat fertilizat',
        'arat cultivat semanat',
        'arat cultivat plantat',
        'arat plantat fertilizat',
        'arat plantat semanat',
        'arat plantat cultivat',
        'fertilizat arat semanat',
        'fertilizat arat cultivat',
        'fertilizat arat plantat',
        'fertilizat semanat arat',
        'fertilizat semanat cultivat',
        'fertilizat semanat plantat',
        'fertilizat cultivat arat',
        'fertilizat cultivat semanat',
        'fertilziat cultivat plantat',
        'fertilizat plantat arat',
        'fertilizat plantat semanat',
        'fertilizat plantat cultivat',
        'semanat arat fertilizat',
        'semanat arat cultivat',
        'semanat arat plantat',
        'semanat fertilizat arat',
        'semanat fertilizat cultivat',
        'semanat fertilizat plantat',
        'semanat cultivat arat',
        'semanat cultivat fertilizat',
        'semanat cultivat plantat',
        'semanat plantat arat',
        'semanat plantat fertilizat',
        'semanat plantat cultivat',
        'cultivat arat fertilizat',
        'cultivat arat semanat',
        'cultivat arat plantat',
        'cultivat fertilizat arat',
        'cultivat fertilizat semanat',
        'cultivat fertilizat plantat',
        'cultivat semanat arat',
        'cultivat semanat fertilizat',
        'cultivat semanat plantat',
        'cultivat plantat arat',
        'cultivat plantat fertilizat',
        'cultivat plantat semanat',
        'plantat arat fertilizat',
        'plantat arat semanat',
        'plantat arat cultivat',
        'plantat fertilizat arat',
        'plantat fertilizat semanat',
        'plantat fertilziat cultivat',
        'plantat semanat arat',
        'plantat semanat fertilizat',
        'plantat semanat cultivat',
        'plantat cultivat arat',
        'plantat cultivat fertilizat',
        'plantat cultivat semanat',
        'arat, fertilizat, semanat, cultivat',
        'arat fertilizat semanat plantat',
        'arat fertilizat cultivat semanat',
        'arat fertilizat cultivat plantat',
        'arat fertilizat plantat semanat',
        'arat fertilizat plantat cultivat',
        'arat semanat fertilizat cultivat',
        'arat semanat fertilizat plantat',
        'arat semanat cultivat fertilizat',
        'arat semanat cultivat plantat',
        'arat semanat plantat fertilizat',
        'arat semanat plantat cultivat',
        'arat cultivat fertilizat semanat',
        'arat cultivat fertilizat plantat',
        'arat cultivat semanat fertilizat',
        'arat cultivat semanat plantat',
        'arat cultivat plantat fertilizat',
        'arat cultivat plantat semanat',
        'arat plantat fertilizat semanat',
        'arat plantat fertilizat cultivat',
        'arat plantat semanat fertilizat',
        'arat plantat semanat cultivat',
        'arat plantat cultivat fertilizat',
        'arat plantat cultivat semanat',
        'fertilizat arat semanat cultivat',
        'fertilizat arat semanat plantat',
        'fertilizat arat cultivat semanat',
        'fertilizat arat cultivat plantat',
        'fertilizat arat plantat semanat',
        'fertilizat arat plantat cultivat',
        'fertilizat semanat arat cultivat',
        'fertilizat semanat arat plantat',
        'fertilizat semanat cultivat arat',
        'fertilizat semanat cultivat plantat',
        'fertilizat semanat plantat arat',
        'fertilizat semanat plantat cultivat',
        'fertilizat cultivat arat semanat',
        'fertilizat cultivat arat plantat',
        'fertilizat cultivat semanat arat',
        'fertilizat cultivat semanat plantat',
        'fertilizat cultivat plantat arat',
        'fertilizat cultivat plantat semanat',
        'fertilizat plantat arat semanat',
        'fertilizat plantat arat cultivat',
        'fertilizat plantat semanat arat',
        'fertilizat plantat semanat cultivat',
        'fertilizat plantat cultivat arat',
        'fertilizat plantat cultivat semanat',
        'semanat arat fertilizat cultivat',
        'semanat arat fertilizat plantat',
        'semanat arat cultivat fertilizat',
        'semanat arat cultivat plantat',
        'semanat arat plantat fertilizat',
        'semanat arat plantat cultivat',
        'semanat fertilizat arat cultivat',
        'semanat fertilizat arat plantat',
        'semanat fertilizat cultivat arat',
        'semanat fertilizat cultivat plantat',
        'semanat fertilizat plantat arat',
        'semanat fertilizat plantat cultivat',
        'semanat cultivat arat fertilizat',
        'semanat cultivat arat plantat',
        'semanat cultivat fertilizat arat',
        'semanat cultivat fertilizat plantat',
        'semanat cultivat plantat arat',
        'semanat cultivat plantat fertilizat',
        'semanat plantat arat fertilizat',
        'semanat plantat arat cultivat',
        'semanat plantat fertilizat arat',
        'semanat plantat fertilizat cultivat',
        'semanat plantat cultivat arat',
        'semanat plantat cultivat fertilizat',
        'cultivat arat fertilizat semanat',
        'cultivat arat fertilizat plantat',
        'cultivat arat semanat fertilizat',
        'cultivat arat semanat plantat',
        'cultivat arat plantat fertilizat',
        'cultivat arat plantat semanat',
        'cultivat fertilizat arat semanat',
        'cultivat fertilizat arat plantat',
        'cultivat fertilizat semanat arat',
        'cultivat fertilizat semanat plantat',
        'cultivat fertilizat plantat arat',
        'cultivat fertilizat plantat semanat',
        'cultivat semanat arat fertilizat',
        'cultivat semanat arat plantat',
        'cultivat semanat fertilizat arat',
        'cultivat semanat fertilizat plantat',
        'cultivat semanat plantat arat',
        'cultivat semanat plantat fertilizat',
        'cultivat plantat arat fertilizat',
        'cultivat plantat arat semanat',
        'cultivat plantat fertilizat arat',
        'cultivat plantat fertilizat semanat',
        'cultivat plantat semanat arat',
        'cultivat plantat semanat fertilizat',
        'plantat arat fertilizat semanat',
        'plantat arat fertilizat cultivat',
        'plantat arat semanat fertilizat',
        'plantat arat semanat cultivat',
        'plantat arat cultivat fertilizat',
        'plantat arat cultivat semanat',
        'plantat fertilizat arat semanat',
        'plantat fertilizat arat cultivat',
        'plantat fertilizat semanat arat',
        'plantat fertilizat semanat cultivat',
        'plantat fertilizat cultivat arat',
        'plantat fertilizat cultivat semanat',
        'plantat semanat arat fertilizat',
        'plantat semanat arat cultivat',
        'plantat semanat fertilizat arat',
        'plantat semanat fertilizat cultivat',
        'plantat semanat cultivat arat',
        'plantat semanat cultivat fertilizat',
        'plantat cultivat arat fertilizat',
        'plantat cultivat arat semanat',
        'plantat cultivat fertilizat arat',
        'plantat cultivat fertilizat semanat',
        'plantat cultivat semanat arat',
        'plantat cultivat semanat fertilizat',
      ],
      message: `Această activitate nu există`,
    },
  },

  rented: {
    type: String,
    required: false,
    enum: {
      values: ['Inchiriat', 'Cumparat', 'inchiriat', 'cumparat'],
      message: `Această opțiune nu există`,
    },
  },

  description: String,
  createdAt: {
    type: Date,
    default: Date.now(),
    select: false,
  },
});

tractorSchema.index({ power: 1 });

tractorSchema.pre('save', function (next) {
  this.slug = slugify(this.name, { lower: true });
  next();
});

const Tractor = mongoose.model('Tractor', tractorSchema);

module.exports = Tractor;
